apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: ""
        name: jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-claim0
        - mountPath: /var/run/docker.sock
          name: jenkins-claim1
        - mountPath: /usr/local/bin/docker
          name: jenkins-claim2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: jenkins-claim0
        persistentVolumeClaim:
          claimName: jenkins-claim0
      - name: jenkins-claim1
        persistentVolumeClaim:
          claimName: jenkins-claim1
      - name: jenkins-claim2
        persistentVolumeClaim:
          claimName: jenkins-claim2
status: {}
